### ISSUE TITLE
Remove the Slide from here

### ISSUE THREAD

**Issue by simransingh08** [TeamArKa/VAYUZ-ANAROCK_LEASE#15]
![image](https://github.com/TeamArKa/xploreteq/assets/107848987/7cc4196a-8ab2-443f-89f7-e6e41fcec444)

And put above the "More Articles "
![image](https://github.com/TeamArKa/xploreteq/assets/107848987/d866d336-14f7-4322-994b-1818b121fe78)

**Comment by rahulmvayuz** [comment]
![image](https://github.com/TeamArKa/xploreteq/assets/164298543/c2d1123b-ef9d-4c6a-beea-d8fb3c526a64)
