### ISSUE TITLE
Remove this client logo from here

### ISSUE THREAD

**Issue by simransingh08** [TeamArKa/VAYUZ-ANAROCK_LEASE#16]
![image](https://github.com/TeamArKa/xploreteq/assets/107848987/64b57e30-dcfb-41b8-a34b-ca74b0c63e08)

Put "Herbinger Group" client logo
![image](https://github.com/TeamArKa/xploreteq/assets/107848987/b05b9df3-51cd-4e90-95ff-20cf42e86c00)

**Comment by rahulmvayuz** [comment]
![image](https://github.com/TeamArKa/xploreteq/assets/164298543/b0a88472-72b7-4a8c-936d-fba79bb0ab43)
