### ISSUE TITLE
remove all the Our Partners Dropdown, 

### ISSUE THREAD

**Issue by simransingh08** [TeamArKa/VAYUZ-ANAROCK_LEASE#17]
![image](https://github.com/TeamArKa/xploreteq/assets/107848987/f8c69606-99ad-4d04-8d34-b379efc16967)

only make the partner page, Whenever anyone will click on Our Partner It will open like a Page

**Comment by rahulmvayuz** [comment]
![image](https://github.com/TeamArKa/xploreteq/assets/164298543/31465b0b-b040-4b0a-87d7-f40a8a765fb9)
