### ISSUE TITLE
Click on Discover Now button

### ISSUE THREAD

**Issue by simransingh08** [TeamArKa/VAYUZ-ANAROCK_LEASE#18]
![image](https://github.com/TeamArKa/xploreteq/assets/107848987/14d8ef51-b406-4e68-9537-f5264f3b0cb6)

![image](https://github.com/TeamArKa/xploreteq/assets/107848987/8bc1626b-bea5-4c07-8ea3-84a881f75fe1)
Please put some content regarding Our service on Service Page

**Comment by rahulmvayuz** [comment]
Please explain ?
