### ISSUE TITLE
Change the color of  Enterprises white color to Blue color which is you used for "x" only

### ISSUE THREAD

**Issue by simransingh08** [TeamArKa/VAYUZ-ANAROCK_LEASE#19]
![image](https://github.com/TeamArKa/xploreteq/assets/107848987/4f5128c1-ba61-4794-b4b6-d7ce4b1aa373)

**Comment by rahulmvayuz** [comment]
![image](https://github.com/TeamArKa/xploreteq/assets/164298543/5b1109fe-1d69-4b39-8692-880d9a3d9afe)
