### ISSUE TITLE
Remove Unveiling Success Stories 

### ISSUE THREAD

**Issue by simransingh08** [TeamArKa/VAYUZ-ANAROCK_LEASE#21]
![image](https://github.com/user-attachments/assets/71693eba-3575-4b1c-96b9-c51e30e92e5b)

and put it above the clients
![image](https://github.com/user-attachments/assets/06cc9c99-3ac1-45d5-b433-74c28f5f7efd)

**Comment by rahulmvayuz** [comment]
![image](https://github.com/user-attachments/assets/a38c9ce3-036c-4792-a32d-44a52db94e65)
Done
