### ISSUE TITLE
submit your enquiry

### ISSUE THREAD

**Issue by simransingh08** [TeamArKa/VAYUZ-ANAROCK_LEASE#25]
change the banner
![image](https://github.com/user-attachments/assets/5e32b24f-1526-4faf-9c52-bf21b02ad256)

remove the Get in touch section
![image](https://github.com/user-attachments/assets/1a713469-dc5d-40ae-85bf-b9c09c2ec0b6)

add one more form as well as Free Security Assessment and name will be Data Risk assessment
![image](https://github.com/user-attachments/assets/3c242425-e2ff-4739-9df9-40b97cabc75e)

**Comment by rahulmvayuz** [comment]
![Uploading image.png…]()
Done
