### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by simransingh08** [TeamArKa/VAYUZ-ANAROCK_LEASE#26]
do some changes, if you can provide google map address do it or do something else
![image](https://github.com/user-attachments/assets/ba71c088-3ae8-4c79-8832-3a696faadef9)

do some color combination

**Comment by rahulmvayuz** [comment]
![image](https://github.com/user-attachments/assets/bddfab22-0887-4401-99f6-551681c78e41)
Done
