### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by simransingh08** [TeamArKa/VAYUZ-ANAROCK_LEASE#27]
Our Services
![image](https://github.com/user-attachments/assets/5262702d-f593-4dd2-a95b-6a455a42dd85)

Our Expertise
![image](https://github.com/user-attachments/assets/9a812df0-b82c-4720-8c0d-bea20e1ea241)

Our Partners
![image](https://github.com/user-attachments/assets/045dfd33-af46-4a98-9386-737d1c9a5d3f)

Remove the dummy content from Our Services, Expertise and Partner.

Our Services change to Make an Enquiry, and button name will be Enquiry now

**Comment by rahulmvayuz** [comment]
Please Share content
